import{a as P,S as v,i as l}from"./assets/vendor-DqB7j7Ix.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const B="50800171-f0005a0681d5ee847775b056c",E="https://pixabay.com/api/",A=15;async function f(t,o=1){const a={key:B,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:A,page:o};try{const s=await P.get(E,{params:a});if(s.data.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");return s.data}catch(s){throw s}}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),c=document.querySelector("#loader"),$=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){const o=t.map(({webformatURL:a,largeImageURL:s,tags:e,likes:r,views:i,comments:S,downloads:q})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img src="${a}" alt="${e}" loading="lazy" class="image"/>
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><span> ${r}</span></p>
          <p class="info-item"><b>Views</b><span> ${i}</span></p>
          <p class="info-item"><b>Comments</b><span> ${S}</span></p>
          <p class="info-item"><b>Downloads</b><span> ${q}</span></p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",o),$.refresh()}function H(){m.innerHTML=""}function p(){y.style.display="block",c&&(c.hidden=!1)}function h(){y.style.display="none",c&&(c.hidden=!0)}const b=document.querySelector(".form"),O=b.elements["search-text"],n=document.querySelector("#load-more-btn");let d=1,u="",L=0;b.addEventListener("submit",async t=>{t.preventDefault();const o=O.value.trim();if(!o){l.warning({message:"Please enter a search query."});return}u=o,d=1,H(),n.hidden=!0,p();try{const a=await f(u,d);L=a.totalHits,a.hits.length===0?l.error({message:"Sorry, there are no images matching your search query. Please try again!"}):(g(a.hits),w())}catch{l.error({message:"An error occurred. Please try again later."})}finally{h()}});function x(){const t=document.querySelector(".gallery-item");if(!t)return;const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}n.addEventListener("click",async()=>{d+=1,p(),n.disabled=!0;try{const t=await f(u,d);g(t.hits),setTimeout(()=>{x()},300),w()}catch{l.error({message:"Failed to load more images."})}finally{h(),n.disabled=!1}});function w(){document.querySelectorAll(".gallery-item").length>=L?(n.hidden=!0,l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):n.hidden=!1}
//# sourceMappingURL=index.js.map
